### ISSUE TITLE
Speicher der Anwesenheit

### ISSUE THREAD

**Issue by hkalinke** [hkalinke/4minitz#16]
- analysieren an welcher Stelle in der DB die Checkbox-Option gespeichert wurde
- entsprechend umbauen und nun dort die gewählte Anwesenheitsoption ablegen
- ACHTUNG: Abwärtskompatibilität wahren, alle Meetings müssen noch die Checkboxes darstellen
  - eine Möglichkeit: alle neuen Meetings bekommen ein "Versions"-Feld
  - wenn vorhanden und Wert > irgendwas, dann Select-GUI
  - sonst Checkbox-GUI

**Comment by thrs79136** [comment]
Dateien:
minutes.schema.js (14)
documentGeneration.js (92)
