### ISSUE TITLE
Recherche: Bibliotheken für Übersetzungen

### ISSUE THREAD

**Issue by hkalinke** [hkalinke/4minitz#2]
- Liefert Meteor bereits eine native Möglichkeit?
- Wenn ja, welche? Gut? Schlecht? 
- Alternative Bibliothek?

**Comment by florianfreier** [comment]
Wurde https://i18njs.com vorschlagen.

**Comment by florianfreier** [comment]
Wir haben uns für https://atmospherejs.com/tap/i18n entschieden.
